### PR TITLE
Use correct function and temporary client settings

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
@ericadamski Hey.

So, one fix here uses the correct function for public posts.

Regarding auth. I started refactoring for using token based auth and then stopped, as I realised that you get less privileged access anyway.

I think the error happens due to the url in your application settings no longer existing. I tried with my own settings and then browser based auth works really well.

So, check your server and feel free to put your own settings back. I changed a few settings whilst testing, but I think it was just the url.

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
Also, WebStorm did some formatting, I can revert that if you want.

**Review by ericadamski — APPROVED** [review]
@ChrisChinchilla I will add a .eslint file (see #6) to handle all the styling. The PR looks good! I would like to follow the `gitflow` style of branching which you could read about [here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) and let me know what you think.

**Comment by ChrisChinchilla** [comment]
@ericadamski Yup, fine and familiar with git flow.

**Comment by ericadamski** [comment]
Awesome @ChrisChinchilla!!! Excited that this is going ahead

**Comment by ericadamski** [comment]
This PR is now out of date with master. I will close it for now.

**Pull request closed without merging**
